export const GUILD_NAME: string = process.env.GUILD_NAME || "Games and shit"
export const PREFIX: string = process.env.PREFIX || "!"
export const TOKEN: string = process.env.TOKEN || ""
export const DBLTOKEN: string = process.env.DBLTOKEN || ""
export const GHTOKEN: string = process.env.GHTOKEN || ""
